language: node_js
cache: yarn
branches:
  only:
    master
after_success: yarn run deploy -r https://$GITHUB_TOKEN@github.com/kylev/pen.git/ -m "Travis ${TRAVIS_BUILD_NUMBER} kylev/pen@${TRAVIS_COMMIT}"
