name: Test and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: Deploy
        run: |
          git config --global user.name "Deploy Bot"
          git config --global user.email "kylev@users.noreply.github.com"
          yarn run deploy \
            -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY \
            -m "GH Action ${GITHUB_RUN_NUMBER} kylev/pen@${GITHUB_SHA}"
