name: Test and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
          cache: yarn
      - run: yarn install
      - run: yarn test
      - name: Deploy
        run: |
          git config --global user.name "Deploy Bot"
          git config --global user.email "kylev@users.noreply.github.com"
          yarn run deploy \
            -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY \
            -m "GH Action ${GITHUB_RUN_NUMBER} kylev/pen@${GITHUB_SHA}"
