name: Test and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
          cache: yarn
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - name: Deploy
        run: |
          git config --global user.name "Deploy Bot"
          yarn run deploy -r https://$GITHUB_TOKEN@github.com/kylev/pen.git/ -m "GH Action ${GITHUB_ACTION} kylev/pen@${GITHUB_SHA}"
